FROM almalinux:9
ENV COURSE="DevOps" \
    TRAINER="SIVA_KUMAR" \
    DURATION="120HRS"
ARG STUDENT="KRANTHI_KUMAR"
RUN echo "Hi, Course is :${COURSE}, Trainer is :${TRAINER}, Duration is :${DURATION}, Student is :${STUDENT}"
CMD ["sleep","1000"]